### PR TITLE
added eda_script.py

### PR DESCRIPTION
**Pull request by lennonay**

### CODE REVIEW

**Review by shlrley — CHANGES_REQUESTED** [review]
Very minor change but could you capitalize the words in the titles of the figures (inside `eda_script.py`)? 

i.e:
- "Distribution of predictors for each Risk Level" --> "Distribution of Predictors for Each Risk Level" 
- "Boxplots of different features" --> "Boxplots of Different Features"

**Comment by lennonay** [comment]
> Very minor change but could you capitalize the words in the titles of the figures (inside `eda_script.py`)?
> 
> i.e:
> 
>     * "Distribution of predictors for each Risk Level" --> "Distribution of Predictors for Each Risk Level"
> 
>     * "Boxplots of different features" --> "Boxplots of Different Features"

Sure, the titles should be changed with the latest commit

**Review by lennonay — COMMENTED** [review]
The titles should be changed now

**Comment by shlrley** [comment]
There's a missing closing quote! In: 
`.properties(title='Boxplots of Different Features)`

**Pull request merged**
